# Generated by Django 4.2.4 on 2023-08-16 20:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Credit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('montant_emprunte', models.IntegerField()),
                ('taux_interet', models.IntegerField()),
                ('duree_credit', models.IntegerField()),
                ('date_fincredit', models.DateField()),
                ('date_create', models.DateField(auto_now_add=True)),
                ('ower', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['date_create'],
            },
        ),
    ]
